version: "3.8"

services:
  tutorio-express:
    build: .
    container_name: tutorio-express
    ports:
      - "3000:3000"
    depends_on:
      - tutorio-mongodb
      - tutorio-app
    environment:
      DATABASE_URL: "mongodb://tutorioAdmin:sm8_NhGsqKCuqxUo6Mrv@tutorio-mongodb:27017/mydatabase?authSource=admin&directConnection=true"
    volumes:
      - ./uploads:/app/uploads
      - ./uploads/diplomas:/app/uploads/diplomas

  tutorio-mongodb:
    image: prismagraphql/mongo-single-replica:5.0.3
    container_name: tutorio-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: tutorioAdmin
      MONGO_INITDB_ROOT_PASSWORD: sm8_NhGsqKCuqxUo6Mrv

  tutorio-app:
    build:
      context: ../tutorio-frontend
      args:
        NEXT_PUBLIC_BACKEND_HOST: tutorio-express
        NEXT_PUBLIC_BACKEND_PORT: 3000
        NEXT_PUBLIC_CDN_URL: http://tutorio-express:3000
        NEXT_IMAGE_HOST: tutorio-express
    container_name: tutorio-app
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_HOST=tutorio-express
      - NEXT_PUBLIC_BACKEND_PORT=3000
      - NEXT_PUBLIC_CDN_URL=http://tutorio-express:3000
      - NEXT_IMAGE_HOST=tutorio-express

  nginx:
    image: nginx:latest
    container_name: tutorio-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/robots.txt:/usr/share/nginx/html/robots.txt:ro
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/ssl-data:/var/www/certbot
    depends_on:
      - tutorio-app
      - tutorio-express

  certbot:
    image: certbot/certbot
    container_name: tutorio-certbot
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/ssl-data:/var/www/certbot
    entrypoint: >
      sh -c "certbot certonly --webroot --webroot-path=/var/www/certbot
      --email your-email@example.com --agree-tos --no-eff-email
      -d dev-tutorio.ru -d www.dev-tutorio.ru"

  certbot-renew:
    image: certbot/certbot
    container_name: tutorio-certbot-renew
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/ssl-data:/var/www/certbot
    entrypoint: >
      sh -c "certbot renew --webroot --webroot-path=/var/www/certbot"
