services:
  tutorio-express:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - tutorio-mongodb
    environment:
      DATABASE_URL: "mongodb://tutorioAdmin:sm8_NhGsqKCuqxUo6Mrv@tutorio-mongodb:27017/mydatabase?authSource=admin&directConnection=true"
    volumes:
      - ./uploads:/uploads

  tutorio-mongodb:
    image: prismagraphql/mongo-single-replica:5.0.3
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: tutorioAdmin
      MONGO_INITDB_ROOT_PASSWORD: sm8_NhGsqKCuqxUo6Mrv
